name: secrets
on: push

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: get secrets
        run: echo ${{ secrets.LEVEL }}


  get-secrets2:
    runs-on: ubuntu-latest
    steps:
      - name: get secrets
        run: echo ${{ secrets.level }}
