name: tag-filter
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # v1.0.0 or v2.2.2 등에선 동작, v1.0 or 1.0.0 이런건 동작안함

jobs:
  tag-filter:
    runs-on: ubuntu-latest
    steps:
      - name: echo hello
        run: echo hello
