name: timeout
on: workflow_dispatch

jobs:
  timeout:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: loop
        run: |
          count=0
          while true; do
          echo "seconds: $count"
          count=$((count+1))
          sleep1
          done
      - name: echo
        run: echo hello
